# Generated by Django 3.2 on 2021-05-08 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=45)),
                ('photo', models.ImageField(blank=True, default='man.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('route_id', models.IntegerField()),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('plate', models.CharField(max_length=10)),
                ('seats', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=150)),
                ('owner_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routFrom', mapbox_location_field.models.LocationField(map_attrs={'id': 'unique_id_1'})),
                ('routTo', mapbox_location_field.models.LocationField(map_attrs={'id': 'unique_id_2'})),
                ('maxPassenger', models.IntegerField()),
                ('seatsReserved', models.IntegerField()),
                ('vehicle_id', models.IntegerField()),
                ('price', models.CharField(max_length=15)),
                ('rout_category', models.CharField(choices=[('create', 'create'), ('find', 'find')], default='create', max_length=10)),
                ('departure', models.DateTimeField()),
                ('radius', models.FloatField()),
                ('user_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ShareTheRideApp.customer')),
            ],
        ),
    ]
